### ISSUE TITLE
Export Error: Cannot read properties of undefined (reading '0')

### ISSUE THREAD

**Issue by koenhendriks** [jh3y/vincent-van-git#20]
When trying to export I get the following error:

![image](https://github.com/jh3y/vincent-van-git/assets/4124579/3b940bd2-092d-4061-bfc6-efc6d7f14ad4)

**Comment by cloudy3** [comment]
I'm getting the same error

**Comment by cloudy3** [comment]
I tried this again, with:
1) Creating a new repository
2) git clone https://github.com/your-username/your-repository.git
3) git checkout --orphan main
4) git commit --allow-empty -m "Initial commit"
5) git push origin main

But it gave "repository is not empty" error.

**Comment by myztajay** [comment]
The issues seems to be that wrote his code to parse for ```blankslate``` in the commit history in the array that is returned. when you look up a repo.


When you create a new repo,  until you actually  commit this page doesn't seem to be generated. Meaning that fetch request returns nothing.  I'm curious why he didn't use the api and just check if the commit array is empty?
