### ISSUE TITLE
"blankslate" No longer is returned when a repo has no commits.

### ISSUE THREAD

**Issue by myztajay** [jh3y/vincent-van-git#23]
https://github.com/jh3y/vincent-van-git/blob/b30d921f597a48b4b5aeac7ce18c605c4496d261/functions/vincent/vincent.js#L20C23-L20C35

Tool cannot be used because:
1. if you have any commit you are blocked by repo not empty error
2. If you have no commit `blankslate` is not found within data returned from fetch.

**Comment by dayoolacodes** [comment]
hi @jh3y this is still not resolved

**Comment by jh3y** [comment]
Jus' cloned and checked this myself. It works. 

If you can provide more details then I can look into it. I jus' created this with it though.

![CleanShot 2024-07-21 at 18 25 59@2x](https://github.com/user-attachments/assets/a103e7f0-4011-46df-b85d-58f53ead2508)
