### ISSUE TITLE
Can't create empty repo because it is not empty after first commit

### ISSUE THREAD

**Issue by ItsMeBrille** [jh3y/vincent-van-git#24]
I need help creating an empty repo. I am faced with the problem `branch does not exist`. The only way I could find to create a branch is to commit something to the repo, which makes it - *you guessed it* - not empty.

I would believe you probably have a workaround for this, but I couldn't find it.

Thanks in advance

**Comment by jh3y** [comment]
When you create a new repo, the `main` branch will exist by default (Might have to double-check in your settings).
