### ISSUE TITLE
Server issues?

### ISSUE THREAD

**Issue by ExpDev07** [jh3y/vincent-van-git#4]
Getting repository not found on https://github.com/ExpDev07/vincent-van-git-graph.

**Comment by jh3y** [comment]
Yeah, that's strange. I checked and you're correct. It says the repo doesn't exist 🤔 
However, that said. The repository must be empty, no files committed or anything. Wondering if the error message being sent back is incorrect in this case.

**Comment by ExpDev07** [comment]
I tried completely empty also. Still got the same error.

**Comment by jh3y** [comment]
Deploying now 🤦  Silly error on my behalf.

Thank you so much for pointing this out to me 👍 🙏

**Comment by ExpDev07** [comment]
@jh3y I saw. No worries. Awesome tool!

**Comment by jh3y** [comment]
Tested now with your username and repo and it works! 🎉

**Comment by jh3y** [comment]
And thank you! 🙏
